sudo: required
services:
    - docker

before_install:
    - docker build -t pratikjoy7/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pratikjoy7/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-beanstalk-test"
    env: "DockerBeanstalkTest-env"
    bucket_name: "elasticbeanstalk-us-east-1-359067941545"
    bucket_path: "docker-beanstalk-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
